// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/designs": {
    params: {};
  };
  "/designs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/digital-wedding-invitations": {
    params: {};
  };
  "/wedding-rsvp": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/designs" | "/designs/:slug" | "/digital-wedding-invitations" | "/wedding-rsvp" | "/pricing" | "/faq" | "/contact" | "/*";
  };
  "layouts/RootLayout.tsx": {
    id: "layouts/RootLayout";
    page: "/" | "/designs" | "/designs/:slug" | "/digital-wedding-invitations" | "/wedding-rsvp" | "/pricing" | "/faq" | "/contact" | "/*";
  };
  "pages/HomePage.tsx": {
    id: "pages/HomePage";
    page: "/";
  };
  "pages/DesignsPage.tsx": {
    id: "pages/DesignsPage";
    page: "/designs";
  };
  "pages/DesignDetailPage.tsx": {
    id: "pages/DesignDetailPage";
    page: "/designs/:slug";
  };
  "pages/DigitalWeddingInvitationsPage.tsx": {
    id: "pages/DigitalWeddingInvitationsPage";
    page: "/digital-wedding-invitations";
  };
  "pages/WeddingRSVPPage.tsx": {
    id: "pages/WeddingRSVPPage";
    page: "/wedding-rsvp";
  };
  "pages/PricingPage.tsx": {
    id: "pages/PricingPage";
    page: "/pricing";
  };
  "pages/FAQPage.tsx": {
    id: "pages/FAQPage";
    page: "/faq";
  };
  "pages/ContactPage.tsx": {
    id: "pages/ContactPage";
    page: "/contact";
  };
  "pages/NotFoundPage.tsx": {
    id: "pages/NotFoundPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/RootLayout": typeof import("./src/layouts/RootLayout.tsx");
  "pages/HomePage": typeof import("./src/pages/HomePage.tsx");
  "pages/DesignsPage": typeof import("./src/pages/DesignsPage.tsx");
  "pages/DesignDetailPage": typeof import("./src/pages/DesignDetailPage.tsx");
  "pages/DigitalWeddingInvitationsPage": typeof import("./src/pages/DigitalWeddingInvitationsPage.tsx");
  "pages/WeddingRSVPPage": typeof import("./src/pages/WeddingRSVPPage.tsx");
  "pages/PricingPage": typeof import("./src/pages/PricingPage.tsx");
  "pages/FAQPage": typeof import("./src/pages/FAQPage.tsx");
  "pages/ContactPage": typeof import("./src/pages/ContactPage.tsx");
  "pages/NotFoundPage": typeof import("./src/pages/NotFoundPage.tsx");
};